<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ManagedPlugin>true</ManagedPlugin>
    <ManagedPluginId>myavalonia.plugin.workflow-studio</ManagedPluginId>
    <ManagedPluginDirectoryName>WorkflowStudio</ManagedPluginDirectoryName>
    <PluginVersion>1.1.0</PluginVersion>
    <ManagedPluginRuntimeIdentifier>win-x64</ManagedPluginRuntimeIdentifier>
    <ManagedPluginEntryType>WorkflowStudio.Plugin.WorkflowStudioModule</ManagedPluginEntryType>
    <ManagedPluginSdkMinInclusive>3.2.0</ManagedPluginSdkMinInclusive>
    <ManagedPluginSdkMaxExclusive>4.0.0</ManagedPluginSdkMaxExclusive>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="MyAvaloniaManagement.Plugin.Build" PrivateAssets="all" />
    <PackageReference Include="MyAvaloniaManagement.PluginSdk" />
    <PackageReference Include="MyAvaloniaManagement.PluginSdk.Workflow" />
    <PackageReference Include="MyAvaloniaManagement.PluginSdk.UI" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WorkflowStudio.Tests" />
  </ItemGroup>

</Project>
